# LTW core sources (GL ES wrapper library)
set(LTW_CORE_SRC
  ${LTW_DIR}/egl.c
  ${LTW_DIR}/proc.c
  ${LTW_DIR}/main.c
  ${LTW_DIR}/glformats.c
  ${LTW_DIR}/basevertex.c
  ${LTW_DIR}/blending.c
  ${LTW_DIR}/query.c
  ${LTW_DIR}/shader_wrapper.c
  ${LTW_DIR}/string_utils.c
  ${LTW_DIR}/framebuffer.c
  ${LTW_DIR}/of_buffer_copier.c
  ${LTW_DIR}/stubs.c
  ${LTW_DIR}/multidraw.c
  ${LTW_DIR}/vertexattrib.c
  ${LTW_DIR}/swizzle.c
  ${LTW_DIR}/license_notice.c
  ${LTW_DIR}/env.c
  ${LTW_DIR}/vgpu_shaderconv/shaderconv.c
  ${LTW_DIR}/unordered_map/unordered_map.c
  ${LTW_DIR}/unordered_map/int_hash.c
)
