#!/usr/bin/env python3
"""
Encrypt WitchConfig values with AES-256-CBC + HMAC-SHA256 (Encrypt-then-MAC) using WITCH_ENCRYPTION_KEY (64 hex chars = 32 bytes).
This matches WitchCrypto.m (CommonCrypto CBC, available on iOS) for at-rest + transport.
Outputs Natives/Config/WitchConfig.h with obfuscated master key and enc_v1:<base64> values.

Usage:
  python3 scripts/encrypt_witch_config.py \
    --key-hex $WITCH_ENCRYPTION_KEY \
    --base-url "$WITCH_BASE_URL" \
    --hmac "$WITCH_HMAC_SECRET" \
    --token "$WITCH_PROXY_TOKEN" \
    --curseforge-key "$WITCH_CURSEFORGE_API_KEY" \
    --out Natives/Config/WitchConfig.h

If --key-hex is empty/missing, generates plain (non-encrypted) WitchConfig.h for public builds.
No secrets are printed to stdout in plain; only prefix enc_v1:*** is shown.
"""
import argparse
import os
import sys
import secrets
import base64
import string

try:
    from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
    from cryptography.hazmat.primitives import padding, hashes, hmac
    HAS_CRYPTO = True
except ImportError:
    HAS_CRYPTO = False

def aes_cbc_hmac_encrypt(key_bytes: bytes, plaintext: str) -> str:
    if not plaintext:
        return ""
    if not HAS_CRYPTO:
        print("ERROR: cryptography package not available. Install with: pip install cryptography", file=sys.stderr)
        sys.exit(1)
    # 16-byte random IV for CBC
    iv = secrets.token_bytes(16)
    # PKCS7 pad
    padder = padding.PKCS7(128).padder()
    padded = padder.update(plaintext.encode('utf-8')) + padder.finalize()
    cipher = Cipher(algorithms.AES(key_bytes), modes.CBC(iv))
    encryptor = cipher.encryptor()
    ct = encryptor.update(padded) + encryptor.finalize()
    # HMAC-SHA256 over iv || ct, truncated to 16 bytes (Encrypt-then-MAC, same as WitchCrypto.m)
    h = hmac.HMAC(key_bytes, hashes.SHA256())
    h.update(iv + ct)
    full_hmac = h.finalize()
    tag = full_hmac[:16]
    combined = iv + ct + tag  # iv(16) + ct + tag(16)
    b64 = base64.b64encode(combined).decode('ascii')
    return f"enc_v1:{b64}"

def obfuscate_key(key_bytes: bytes):
    salt = secrets.randbits(8)
    obf = bytes(b ^ salt ^ (i & 0xFF) for i, b in enumerate(key_bytes))
    b64 = base64.b64encode(obf).decode('ascii')
    return salt, b64

def is_hex(s: str, length: int) -> bool:
    if len(s) != length:
        return False
    return all(c in string.hexdigits for c in s)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--key-hex', default=os.environ.get('WITCH_ENCRYPTION_KEY', ''))
    parser.add_argument('--base-url', default=os.environ.get('WITCH_BASE_URL', ''))
    parser.add_argument('--hmac', default=os.environ.get('WITCH_HMAC_SECRET', ''))
    parser.add_argument('--token', default=os.environ.get('WITCH_PROXY_TOKEN', ''))
    parser.add_argument('--curseforge-key', default=os.environ.get('WITCH_CURSEFORGE_API_KEY', ''))
    parser.add_argument('--out', required=True)
    parser.add_argument('--print-masked', action='store_true', help='Print masked output (no plain)')
    parser.add_argument('--server-only', action='store_true', help='Server-only master key: header will NOT contain WITCH_ENCRYPTION_KEY, client holds only enc values and sends them directly')
    args = parser.parse_args()

    key_hex = (args.key_hex or "").strip()
    if not key_hex:
        key_hex = os.environ.get('WITCH_KEY_HEX', '').strip()

    out_path = args.out
    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    if not key_hex:
        print("[encrypt] No WITCH_ENCRYPTION_KEY set — generating PLAIN WitchConfig.h (public build)")
        content = f"""#pragma once
// Public build — no encryption (WITCH_ENCRYPTION_KEY not set)
// Generated by scripts/encrypt_witch_config.py
#define WITCH_ENCRYPTION_ENABLED 0
#define WITCH_DEFAULT_BASE_URL @"{args.base_url}"
#define WITCH_DEFAULT_HMAC_SECRET @"{args.hmac}"
#define WITCH_DEFAULT_PROXY_TOKEN @"{args.token}"
#define WITCH_DEFAULT_CURSEFORGE_API_KEY @"{args.curseforge_key}"
"""
        with open(out_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"[encrypt] Wrote plain config to {out_path}")
        return 0

    if not is_hex(key_hex, 64):
        print(f"ERROR: WITCH_ENCRYPTION_KEY must be 64 hex chars (32 bytes), got {len(key_hex)} chars", file=sys.stderr)
        sys.exit(1)
    try:
        key_bytes = bytes.fromhex(key_hex)
    except Exception as e:
        print(f"ERROR: invalid hex: {e}", file=sys.stderr)
        sys.exit(1)
    if len(key_bytes) != 32:
        print(f"ERROR: key must be 32 bytes, got {len(key_bytes)}", file=sys.stderr)
        sys.exit(1)

    if not HAS_CRYPTO:
        print("ERROR: Need 'cryptography' package. Installing...", file=sys.stderr)
        sys.exit(1)

    salt, obf_b64 = obfuscate_key(key_bytes)

    def enc(val: str) -> str:
        if not val:
            return ""
        return aes_cbc_hmac_encrypt(key_bytes, val)

    enc_base = enc(args.base_url)
    enc_hmac = enc(args.hmac)
    enc_token = enc(args.token)
    enc_cf = enc(args.curseforge_key)

    if args.server_only:
        # Server-only mode: master key stays ONLY on server, client holds ONLY pre-encrypted token.
        # Base URL and HMAC are left plain so client can still construct URL and HMAC without master key.
        # Only WITCH_PROXY_TOKEN is pre-encrypted (static enc_v1), client sends it directly as Bearer.
        # This way binary never contains WITCH_ENCRYPTION_KEY, only the ciphertext.
        content = f"""#pragma once
// Encrypted build — SERVER-ONLY master key (WITCH_ENCRYPTION_KEY only on server)
// Generated by scripts/encrypt_witch_config.py --server-only — DO NOT COMMIT REAL SECRETS
// Client holds ONLY enc_v1 for proxy token, NO master key. Server decrypts enc_v1 with WITCH_ENCRYPTION_KEY and compares to plain.
// HMAC and base URL are left plain (or empty) so client can still generate HMAC without master key. For public endpoints HMAC is optional anyway.
// Values are enc_v1:<base64(iv16+ct+tag16)>
#define WITCH_ENCRYPTION_ENABLED 0
#define WITCH_PRE_ENCRYPTED 1
#define WITCH_DEFAULT_BASE_URL @"{args.base_url}"
#define WITCH_DEFAULT_HMAC_SECRET @"{args.hmac}"
#define WITCH_DEFAULT_PROXY_TOKEN @"{enc_token}"
#define WITCH_DEFAULT_CURSEFORGE_API_KEY @"{args.curseforge_key}"
"""
    else:
        content = f"""#pragma once
// Encrypted build — AES-256-CBC + HMAC-SHA256 (WITCH_ENCRYPTION_KEY set)
// Generated by scripts/encrypt_witch_config.py — DO NOT EDIT MANUALLY, DO NOT COMMIT REAL SECRETS
// Master key is obfuscated (XOR salt+index, base64). Values are enc_v1:<base64(iv16+ct+tag16)>
#define WITCH_ENCRYPTION_ENABLED 1
#define WITCH_ENCRYPTION_KEY_SALT {salt}
#define WITCH_ENCRYPTION_KEY_OBF_B64 @"{obf_b64}"
#define WITCH_DEFAULT_BASE_URL @"{enc_base}"
#define WITCH_DEFAULT_HMAC_SECRET @"{enc_hmac}"
#define WITCH_DEFAULT_PROXY_TOKEN @"{enc_token}"
#define WITCH_DEFAULT_CURSEFORGE_API_KEY @"{enc_cf}"
"""
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(content)

    def mask(s: str) -> str:
        if not s:
            return "(empty)"
        if s.startswith("enc_v1:"):
            return s[:9] + "***" + f"({len(s)} chars)"
        return "***"
    print(f"[encrypt] Wrote ENCRYPTED config to {out_path}")
    print(f"  WITCH_ENCRYPTION_KEY_SALT={salt} WITCH_ENCRYPTION_KEY_OBF_B64={obf_b64[:8]}***")
    print(f"  WITCH_DEFAULT_BASE_URL={mask(enc_base)}")
    print(f"  WITCH_DEFAULT_HMAC_SECRET={mask(enc_hmac)}")
    print(f"  WITCH_DEFAULT_PROXY_TOKEN={mask(enc_token)}")
    print(f"  WITCH_DEFAULT_CURSEFORGE_API_KEY={mask(enc_cf)}")
    print("[encrypt] Done. Master key is obfuscated, values are AES-256-CBC+HMAC encrypted.")
    return 0

if __name__ == '__main__':
    sys.exit(main())
